name: BLOG build

on: push

jobs:
  blog-build:
    name: BLOG Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: NPM install and build
        run: |
          sudo su
          npm install -g hexo-cli
          npm install
          hexo generate
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
